### ISSUE TITLE
PHP function or class missing

### ISSUE THREAD

**Issue by 2braincells2go** [salamcast/eKatab#1]
Thanks for sharing, had seen this some time ago and now renewed interest:)

Installed and added ePub book and get the message below when clicking to read:

```
RESTphulSrv Error | php_fail

PHP function or class missing
XSLTProcessor not found
```

Also under the ePubs area see a bar which links to http://xxxxxxxxxxx/epub/RESTful_Web_Services.php. Pretty sure that is not suppose to be there...

Any ideas where to start troubleshooting?

Woody

**Comment by 2braincells2go** [comment]
My bad, looked at VPS and thought had php5-xsl extension installed but did not. That would be the issue...

**Comment by holz-one** [comment]
Yes sir,
This app requires xslt support in pho, so MAMP and XAMPP on Windows will also not work, since they don't include php-xsl.

Im going to have to update my readme, thanks for the feed back!

Karl

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.6.34&pv=5.0&source=email_footer_2] On Fri, Aug 05, 2016 at 10:12 PM, Woody < notifications@github.com [notifications@github.com] > wrote:
My bad, looked at VPS and thought had php5-xsl extension installed but did not. That would be the issue...
